export let locationsCTX = {
  "Links Pocket":                                         null,
  "Queen Gohma":                                          null,
  "King Dodongo":                                         null,
  "Barinade":                                             null,
  "Phantom Ganon":                                        null,
  "Volvagia":                                             null,
  "Morpha":                                               null,
  "Bongo Bongo":                                          null,
  "Twinrova":                                             null,
  "Song from Impa":                                       null,
  "Song from Malon":                                      null,
  "Song from Saria":                                      null,
  "Song from Royal Familys Tomb":                         null,
  "Song from Ocarina of Time":                            null,
  "Song from Windmill":                                   null,
  "Sheik in Forest":                                      null,
  "Sheik in Crater":                                      null,
  "Sheik in Ice Cavern":                                  null,
  "Sheik at Colossus":                                    null,
  "Sheik in Kakariko":                                    null,
  "Sheik at Temple":                                      null,
  "KF Midos Top Left Chest":                              null,
  "KF Midos Top Right Chest":                             null,
  "KF Midos Bottom Left Chest":                           null,
  "KF Midos Bottom Right Chest":                          null,
  "KF Storms Grotto Chest":                               null,
  "LW Ocarina Memory Game":                               null,
  "LW Target in Woods":                                   null,
  "LW Near Shortcuts Grotto Chest":                       null,
  "Deku Theater Skull Mask":                              null,
  "Deku Theater Mask of Truth":                           null,
  "LW Skull Kid":                                         null,
  "LW Deku Scrub Near Bridge":                            null,
  "LW Deku Scrub Grotto Front":                           null,
  "SFM Wolfos Grotto Chest":                              null,
  "HF Near Market Grotto Chest":                          null,
  "HF Tektite Grotto Freestanding PoH":                   null,
  "HF Southeast Grotto Chest":                            null,
  "HF Open Grotto Chest":                                 null,
  "HF Deku Scrub Grotto":                                 null,
  "Market Shooting Gallery Reward":                       null,
  "Market Bombchu Bowling First Prize":                   null,
  "Market Bombchu Bowling Second Prize":                  null,
  "Market Lost Dog":                                      null,
  "Market Treasure Chest Game Reward":                    null,
  "Market 10 Big Poes":                                   null,
  "ToT Light Arrows Cutscene":                            null,
  "HC Great Fairy Reward":                                null,
  "LLR Talons Chickens":                                  null,
  "LLR Freestanding PoH":                                 null,
  "Kak Anju as Child":                                    null,
  "Kak Anju as Adult":                                    null,
  "Kak Impas House Freestanding PoH":                     null,
  "Kak Windmill Freestanding PoH":                        null,
  "Kak Man on Roof":                                      null,
  "Kak Open Grotto Chest":                                null,
  "Kak Redead Grotto Chest":                              null,
  "Kak Shooting Gallery Reward":                          null,
  "Kak 10 Gold Skulltula Reward":                         null,
  "Kak 20 Gold Skulltula Reward":                         null,
  "Kak 30 Gold Skulltula Reward":                         null,
  "Kak 40 Gold Skulltula Reward":                         null,
  "Kak 50 Gold Skulltula Reward":                         null,
  "Graveyard Shield Grave Chest":                         null,
  "Graveyard Heart Piece Grave Chest":                    null,
  "Graveyard Royal Familys Tomb Chest":                   null,
  "Graveyard Freestanding PoH":                           null,
  "Graveyard Dampe Gravedigging Tour":                    null,
  "Graveyard Dampe Race Hookshot Chest":                  null,
  "Graveyard Dampe Race Freestanding PoH":                null,
  "DMT Freestanding PoH":                                 null,
  "DMT Chest":                                            null,
  "DMT Storms Grotto Chest":                              null,
  "DMT Great Fairy Reward":                               null,
  "DMT Biggoron":                                         null,
  "GC Darunias Joy":                                      null,
  "GC Pot Freestanding PoH":                              null,
  "GC Rolling Goron as Child":                            null,
  "GC Rolling Goron as Adult":                            null,
  "GC Maze Left Chest":                                   null,
  "GC Maze Right Chest":                                  null,
  "GC Maze Center Chest":                                 null,
  "DMC Volcano Freestanding PoH":                         null,
  "DMC Wall Freestanding PoH":                            null,
  "DMC Upper Grotto Chest":                               null,
  "DMC Great Fairy Reward":                               null,
  "ZR Open Grotto Chest":                                 null,
  "ZR Frogs in the Rain":                                 null,
  "ZR Frogs Ocarina Game":                                null,
  "ZR Near Open Grotto Freestanding PoH":                 null,
  "ZR Near Domain Freestanding PoH":                      null,
  "ZD Diving Minigame":                                   null,
  "ZD Chest":                                             null,
  "ZD King Zora Thawed":                                  null,
  "ZF Great Fairy Reward":                                null,
  "ZF Iceberg Freestanding PoH":                          null,
  "ZF Bottom Freestanding PoH":                           null,
  "LH Underwater Item":                                   null,
  "LH Child Fishing":                                     null,
  "LH Adult Fishing":                                     null,
  "LH Lab Dive":                                          null,
  "LH Freestanding PoH":                                  null,
  "LH Sun":                                               null,
  "GV Crate Freestanding PoH":                            null,
  "GV Waterfall Freestanding PoH":                        null,
  "GV Chest":                                             null,
  "GF Chest":                                             null,
  "GF HBA 1000 Points":                                   null,
  "GF HBA 1500 Points":                                   null,
  "Wasteland Chest":                                      null,
  "Colossus Great Fairy Reward":                          null,
  "Colossus Freestanding PoH":                            null,
  "OGC Great Fairy Reward":                               null,
  "Deku Tree Map Chest":                                  null,
  "Deku Tree Slingshot Room Side Chest":                  null,
  "Deku Tree Slingshot Chest":                            null,
  "Deku Tree Compass Chest":                              null,
  "Deku Tree Compass Room Side Chest":                    null,
  "Deku Tree Basement Chest":                             null,
  "Deku Tree Queen Gohma Heart":                          null,
  "Dodongos Cavern Map Chest":                            null,
  "Dodongos Cavern Compass Chest":                        null,
  "Dodongos Cavern Bomb Flower Platform Chest":           null,
  "Dodongos Cavern Bomb Bag Chest":                       null,
  "Dodongos Cavern End of Bridge Chest":                  null,
  "Dodongos Cavern Boss Room Chest":                      null,
  "Dodongos Cavern King Dodongo Heart":                   null,
  "Jabu Jabus Belly Boomerang Chest":                     null,
  "Jabu Jabus Belly Map Chest":                           null,
  "Jabu Jabus Belly Compass Chest":                       null,
  "Jabu Jabus Belly Barinade Heart":                      null,
  "Bottom of the Well Front Left Fake Wall Chest":        null,
  "Bottom of the Well Front Center Bombable Chest":       null,
  "Bottom of the Well Back Left Bombable Chest":          null,
  "Bottom of the Well Underwater Left Chest":             null,
  "Bottom of the Well Freestanding Key":                  null,
  "Bottom of the Well Compass Chest":                     null,
  "Bottom of the Well Center Skulltula Chest":            null,
  "Bottom of the Well Right Bottom Fake Wall Chest":      null,
  "Bottom of the Well Fire Keese Chest":                  null,
  "Bottom of the Well Like Like Chest":                   null,
  "Bottom of the Well Map Chest":                         null,
  "Bottom of the Well Underwater Front Chest":            null,
  "Bottom of the Well Invisible Chest":                   null,
  "Bottom of the Well Lens of Truth Chest":               null,
  "Forest Temple First Room Chest":                       null,
  "Forest Temple First Stalfos Chest":                    null,
  "Forest Temple Raised Island Courtyard Chest":          null,
  "Forest Temple Map Chest":                              null,
  "Forest Temple Well Chest":                             null,
  "Forest Temple Eye Switch Chest":                       null,
  "Forest Temple Chest":                                  null,
  "Forest Temple Floormaster Chest":                      null,
  "Forest Temple Red Poe Chest":                          null,
  "Forest Temple Bow Chest":                              null,
  "Forest Temple Blue Poe Chest":                         null,
  "Forest Temple Falling Ceiling Room Chest":             null,
  "Forest Temple Basement Chest":                         null,
  "Forest Temple Phantom Ganon Heart":                    null,
  "Fire Temple Near Boss Chest":                          null,
  "Fire Temple Flare Dancer Chest":                       null,
  "Fire Temple Chest":                                    null,
  "Fire Temple Big Lava Room Lower Open Door Chest":      null,
  "Fire Temple Big Lava Room Blocked Door Chest":         null,
  "Fire Temple Boulder Maze Lower Chest":                 null,
  "Fire Temple Boulder Maze Side Room Chest":             null,
  "Fire Temple Map Chest":                                null,
  "Fire Temple Boulder Maze Shortcut Chest":              null,
  "Fire Temple Boulder Maze Upper Chest":                 null,
  "Fire Temple Scarecrow Chest":                          null,
  "Fire Temple Compass Chest":                            null,
  "Fire Temple Megaton Hammer Chest":                     null,
  "Fire Temple Highest Goron Chest":                      null,
  "Fire Temple Volvagia Heart":                           null,
  "Water Temple Compass Chest":                           null,
  "Water Temple Map Chest":                               null,
  "Water Temple Cracked Wall Chest":                      null,
  "Water Temple Torches Chest":                           null,
  "Water Temple Chest":                                   null,
  "Water Temple Central Pillar Chest":                    null,
  "Water Temple Central Bow Target Chest":                null,
  "Water Temple Longshot Chest":                          null,
  "Water Temple River Chest":                             null,
  "Water Temple Dragon Chest":                            null,
  "Water Temple Morpha Heart":                            null,
  "Shadow Temple Map Chest":                              null,
  "Shadow Temple Hover Boots Chest":                      null,
  "Shadow Temple Compass Chest":                          null,
  "Shadow Temple Early Silver Rupee Chest":               null,
  "Shadow Temple Invisible Blades Visible Chest":         null,
  "Shadow Temple Invisible Blades Invisible Chest":       null,
  "Shadow Temple Falling Spikes Lower Chest":             null,
  "Shadow Temple Falling Spikes Upper Chest":             null,
  "Shadow Temple Falling Spikes Switch Chest":            null,
  "Shadow Temple Invisible Spikes Chest":                 null,
  "Shadow Temple Freestanding Key":                       null,
  "Shadow Temple Wind Hint Chest":                        null,
  "Shadow Temple After Wind Enemy Chest":                 null,
  "Shadow Temple After Wind Hidden Chest":                null,
  "Shadow Temple Spike Walls Left Chest":                 null,
  "Shadow Temple Chest":                                  null,
  "Shadow Temple Invisible Floormaster Chest":            null,
  "Shadow Temple Bongo Bongo Heart":                      null,
  "Spirit Temple Child Bridge Chest":                     null,
  "Spirit Temple Child Early Torches Chest":              null,
  "Spirit Temple Child Climb North Chest":                null,
  "Spirit Temple Child Climb East Chest":                 null,
  "Spirit Temple Map Chest":                              null,
  "Spirit Temple Sun Block Room Chest":                   null,
  "Spirit Temple Silver Gauntlets Chest":                 null,
  "Spirit Temple Compass Chest":                          null,
  "Spirit Temple Early Adult Right Chest":                null,
  "Spirit Temple First Mirror Left Chest":                null,
  "Spirit Temple First Mirror Right Chest":               null,
  "Spirit Temple Statue Room Northeast Chest":            null,
  "Spirit Temple Statue Room Hand Chest":                 null,
  "Spirit Temple Near Four Armos Chest":                  null,
  "Spirit Temple Hallway Right Invisible Chest":          null,
  "Spirit Temple Hallway Left Invisible Chest":           null,
  "Spirit Temple Mirror Shield Chest":                    null,
  "Spirit Temple Chest":                                  null,
  "Spirit Temple Topmost Chest":                          null,
  "Spirit Temple Twinrova Heart":                         null,
  "Ice Cavern Map Chest":                                 null,
  "Ice Cavern Compass Chest":                             null,
  "Ice Cavern Iron Boots Chest":                          null,
  "Ice Cavern Freestanding PoH":                          null,
  "Gerudo Training Ground Lobby Left Chest":              null,
  "Gerudo Training Ground Lobby Right Chest":             null,
  "Gerudo Training Ground Stalfos Chest":                 null,
  "Gerudo Training Ground Before Heavy Block Chest":      null,
  "Gerudo Training Ground Heavy Block First Chest":       null,
  "Gerudo Training Ground Heavy Block Second Chest":      null,
  "Gerudo Training Ground Heavy Block Third Chest":       null,
  "Gerudo Training Ground Heavy Block Fourth Chest":      null,
  "Gerudo Training Ground Eye Statue Chest":              null,
  "Gerudo Training Ground Near Scarecrow Chest":          null,
  "Gerudo Training Ground Hammer Room Clear Chest":       null,
  "Gerudo Training Ground Hammer Room Switch Chest":      null,
  "Gerudo Training Ground Freestanding Key":              null,
  "Gerudo Training Ground Maze Right Central Chest":      null,
  "Gerudo Training Ground Maze Right Side Chest":         null,
  "Gerudo Training Ground Underwater Silver Rupee Chest": null,
  "Gerudo Training Ground Beamos Chest":                  null,
  "Gerudo Training Ground Hidden Ceiling Chest":          null,
  "Gerudo Training Ground Maze Path First Chest":         null,
  "Gerudo Training Ground Maze Path Second Chest":        null,
  "Gerudo Training Ground Maze Path Third Chest":         null,
  "Gerudo Training Ground Maze Path Final Chest":         null,
  "Ganons Castle Forest Trial Chest":                     null,
  "Ganons Castle Water Trial Left Chest":                 null,
  "Ganons Castle Water Trial Right Chest":                null,
  "Ganons Castle Shadow Trial Front Chest":               null,
  "Ganons Castle Shadow Trial Golden Gauntlets Chest":    null,
  "Ganons Castle Light Trial First Left Chest":           null,
  "Ganons Castle Light Trial Second Left Chest":          null,
  "Ganons Castle Light Trial Third Left Chest":           null,
  "Ganons Castle Light Trial First Right Chest":          null,
  "Ganons Castle Light Trial Second Right Chest":         null,
  "Ganons Castle Light Trial Third Right Chest":          null,
  "Ganons Castle Light Trial Invisible Enemies Chest":    null,
  "Ganons Castle Light Trial Lullaby Chest":              null,
  "Ganons Castle Spirit Trial Crystal Switch Chest":      null,
  "Ganons Castle Spirit Trial Invisible Chest":           null,
  "Ganons Tower Chest":                                   null
};